apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: demo
  labels:
    app: redis
data:
  redis.conf: |
    dir /var/lib/redis
    maxmemory 400mb
    save 3600 1
    save 300 10
    save 60 100
    appendonly yes
    protected-mode no