apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
  namespace: demo
  labels:
    name: redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-redis-gp2
  resources:
    requests:
      storage: 5Gi
